CREATE TABLE goals (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  goal_description TEXT DEFAULT NULL,
  goal_type ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'ANNUAL') NOT NULL,
  goal_status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') DEFAULT 'PENDING' NOT NULL,
  goal_priority ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
